### ISSUE TITLE
Plugin cannot be loaded for FF14CN, maybe api9 is needed?

### ISSUE THREAD

**Issue by zytadam** [a08381/Dalamud.SkipCutscene#22]
Plugin cannot be loaded for FF14CN, maybe api9 is needed? Hope for a quick fix, appreciate!

**Comment by a08381** [comment]
你自己下旧版本装进去吧

**Comment by zytadam** [comment]
Api9 version: https://raw.githubusercontent.com/a08381/Dalamud.SkipCutscene/81017cc5fcb9ed8acd9a11acde01e8b05d90397d/latest.zip
