### ISSUE TITLE
Can't get it to work under latest Game Version

### ISSUE THREAD

**Issue by RainerZufahl** [a08381/Dalamud.SkipCutscene#4]
I've tried both the latest official release installed as dev plugin, as well as building the plugin myself from current main branch and putting into dev plugins. It appears in the Plugin List, but shows the following error:

`The Plugin is outdated and incompatible at the moment.`

I was not able to find any API references in the code, or anything else I could easily change myself to make it work. Would love to use this as i just started an alt.

Thank you!

**Comment by RainerZufahl** [comment]
UPDATE: Can be loaded when enabling "Load all API Levels" in Dalamuds Dev Menu, but the plugin doesnt seem to do much? Let me know if it should work right now.

**Comment by a08381** [comment]
you can use repo link to install this plugin, it's not necessary to build it.

`https://github.com/a08381/Dalamud.SkipCutscene/raw/dist/repo.json`

use command `/sc` to enable or disable, when it saids "passed", it works; or "failed", it down.

this plugin is works for skip the cutscene from Castrum Meridianum
or The Praetorium, when it works, these two instance can skip cutscene when you set skip in your character settings.

**Comment by RainerZufahl** [comment]
Oh it's not general for all the cutscenes, then I misunderstood the plugin alltogether. Thank you for the help!
