### ISSUE TITLE
Update to 6.2

### ISSUE THREAD

**Issue by Ari0ner** [a08381/Dalamud.SkipCutscene#7]
Hi! Cant live w/o your plugin! Do you plan to update?

**Comment by a08381** [comment]
It cannot use in 6.2 now？

**Comment by Ari0ner** [comment]
Yea, it didnt work for me last time, said it was outdated and ask to wait for update

**Comment by a08381** [comment]
can it be used in 6.2 now?

**Comment by Ari0ner** [comment]
It works, thanks!
